name: Build and Push Docker Image to GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login --username lokilin14 --password ${{ secrets.GHCR_PERSONAL_ACCESS_TOKEN }} ghcr.io
          docker build -f ./deployment/royal_road_monitor.dockerfile . -t ghcr.io/lokilin14/royal-road-monitor:latest
          docker push ghcr.io/lokilin14/royal-road-monitor:latest

